### ISSUE TITLE
Allow for non fatal error exits of asadmin

### ISSUE THREAD

**Issue by JF9** [eskatos/asadmin#8] opened 2011-04-15 14:46 UTC
If I run asadmin during a clean or during a test phase I might be undeploying an ear that had previously gone wrong, or it may be that it didn't deploy at all.

I'd like the mojo not to fail if it can't undeploy the ear ( or indeed, for example, if the domain is already started).

To do this I'd like to configure the plugin with a regular expression which can be used to match the stderror output when asadmin exits with a non zero status;
<code><pre>
            &lt;plugin&gt;
                &lt;groupId&gt;org.codeartisans.asadmin&lt;/groupId&gt;
                &lt;artifactId&gt;asadmin-maven-plugin&lt;/artifactId&gt;
                &lt;version&gt;0.9-SNAPSHOT&lt;/version&gt;
                &lt;executions&gt;
                    &lt;execution&gt;
                        &lt;id&gt;clean&lt;/id&gt;
                        &lt;phase&gt;clean&lt;/phase&gt;
                        &lt;goals&gt;
                            &lt;goal&gt;undeploy&lt;/goal&gt;
                        &lt;/goals&gt;
                        &lt;configuration&gt;
                            &lt;okayErrorOutputRegex&gt;(?s)._Application My-ear-SNAPSHOT is not deployed on this target._&lt;/okayErrorOutputRegex&gt;
                        &lt;/configuration&gt;
                    &lt;/execution&gt;
                    &lt;execution&gt;
                        &lt;id&gt;start&lt;/id&gt;
                        &lt;phase&gt;pre-integration-test&lt;/phase&gt;
                        &lt;goals&gt;
                            &lt;goal&gt;redeploy&lt;/goal&gt;
                        &lt;/goals&gt;
                    &lt;/execution&gt;
                    &lt;execution&gt;
                        &lt;id&gt;stop&lt;/id&gt;
                        &lt;phase&gt;post-integration-test&lt;/phase&gt;
                        &lt;goals&gt;
                            &lt;goal&gt;undeploy&lt;/goal&gt;
                        &lt;/goals&gt;
                    &lt;/execution&gt;
                &lt;/executions&gt;
            &lt;/plugin&gt;
</pre></code>

To do this you could do  the following

Change IAsAdminCmd and add

<code><pre>
    /**
     \* If asadmin command return is non zero the command will be given the change to say whether they wish to fail based on the contents of stdout and stderr they have been passed.
     \* For example a DeployMojo executing an undeploy command which has failOnCommandSpecificErrors set to false
     \* will elect not to fail if the error output was along the lines of 
     \* "remote failure: Application my-ear is not deployed on this target [server]"
     \* during an mvn clean or testing cycle...
     \* 
     \* @return whether this command should cause the plugin to fail, or whether it is acceptable to continue.
     */
    boolean failOnNonZeroExit();

```
/**
 * Pass a Pattern which can be used to match the stderr output if the asadmin exits with a non zero value.
 * If the Pattern matches the stderr output (multiline) the plugin will not throw an exception but just log the fact that it is continuing
 */
void setOkayErrorPattern(Pattern pattern);
```

</pre></code>

Implement the defaults in AbstractAsAdminCmd

<code><pre>
    @Override
    public boolean failOnNonZeroExit()
    {
        if(okayErrorPattern == null)
            return true;
        else
        {
            return !okayErrorPattern.matcher(stderrBuilder.toString()).matches();
        }
    }

```
@Override
public void setOkayErrorPattern(Pattern pattern) {
    this.okayErrorPattern = pattern;
}
```

</pre></code>

To AbstractAsadminMojo add the following parameter, and compile the Pattern in check
<code> <pre>
  /**
     \* @parameter default-value=""
     */
    protected String okayErrorOutputRegex = null;
    protected Pattern okayErrorOutputPattern = null;

...

```
    if(okayErrorOutputRegex != null && okayErrorOutputRegex.trim().length() != 0)
    {
        try {
            okayErrorOutputPattern = Pattern.compile(okayErrorOutputRegex);
        } catch (PatternSyntaxException e) {
            throw new MojoExecutionException("Cannot compile the okayErrorOutputRegex: ", e );
        } catch(IllegalArgumentException e){
            throw new MojoExecutionException("Cannot compile the okayErrorOutputRegex: ", e );
        } 
    }
```

</pre></code>

In the actual mojo, setup any patterns as acceptable (e.g. UndeployMojo);

<code><pre>
 @Override
    protected AsAdminCmdList getAsCommandList()
    {
        getLog().info( "Undeploying application: " + appName );
        final AsAdminCmdList list = new AsAdminCmdList();
        Deployment deployment = new Deployment().undeploy().component( appName ).target( target );
        deployment.setOkayErrorPattern(okayErrorOutputPattern);
        list.add( deployment );
        return list;
    }
</pre></code>

And lastly in AsAdmin you can check with the command to see what to do in a non zero return from asadmin...

<code><pre>
public void run( final IAsAdminCmd cmd )
            throws AsAdminException
    {
        try {
            final File gfBinPath = new File( config.getGlassfishHome() + File.separator + "bin" );
            final String[] cmds = buildProcessParams( cmd, config );
            cmds[0] = gfBinPath + File.separator + cmds[0];
            int exitCode;
            final Process proc;
            String[] env = buildEnvironmentStrings( config.getEnvironmentVariables() );
            if ( SystemUtils.IS_OS_WINDOWS ) {
                // Windows
                final String command = "\"\"" + StringUtils.join( cmds, "\" \"" ) + "\"\"";
                final String[] windowsCommand;
                if ( SystemUtils.IS_OS_WINDOWS_95 || SystemUtils.IS_OS_WINDOWS_98 || SystemUtils.IS_OS_WINDOWS_ME ) {
                    windowsCommand = new String[]{ "command.com", "/C", command };
                } else {
                    windowsCommand = new String[]{ "cmd.exe", "/C", command };
                }
                outPrintln( "Will run the following command: " + StringUtils.join( windowsCommand, " " ) );
                if(env.length ==0)
                    proc = Runtime.getRuntime().exec( windowsCommand);
                else
                    proc = Runtime.getRuntime().exec( windowsCommand, env );
            } else {
                // Non Windows
                outPrintln( "Will run the following command: " + StringUtils.join( cmds, " " ) );
                proc = Runtime.getRuntime().exec( cmds, env );
            }
            final ProcessStreamGobbler errorGobbler = new ProcessStreamGobbler( cmd,
                                                                                proc.getErrorStream(),
                                                                                ProcessStreamGobbler.ERROR );
            final ProcessStreamGobbler outputGobbler = new ProcessStreamGobbler( cmd,
                                                                                 proc.getInputStream(),
                                                                                 ProcessStreamGobbler.OUTPUT );
            errorGobbler.start();
            outputGobbler.start();
            exitCode = proc.waitFor();
            if ( exitCode != 0 ) {
                if(cmd.failOnNonZeroExit())
                {
                    throw new AsAdminException( "asadmin invocation failed and returned : " + String.valueOf( exitCode ) );
                }
                errPrintln("Ignoring accpetable asadmin error");
            }
        } catch ( final InterruptedException ex ) {
            throw new AsAdminException( "AsAdmin error occurred: " + ex.getMessage(), ex );
        } catch ( final IOException ex ) {
            throw new AsAdminException( "AsAdmin error occurred: " + ex.getMessage(), ex );
        }
    }
</pre></code>

Thanks again, the code is easy to enhance...

**Comment by eskatos** [comment] 2011-04-15 14:59
Hey JF9,

> Thanks again, the code is easy to enhance...

Nice to read, thank you !

What you describe could be a nice feature to add to asadmin-java and asadmin-maven-plugin.
And you did a great job giving all the implementation details.

It would be much better if you could provide a patch that I'll be able to review and apply easily.

The "github way" of doing this is pretty neat and could be usefull if you have some more like this one :)
- Fork the project to your account
- Create a branch named like "feature_failOnNonZeroExit"
- Develop in this branch inside your own fork
- When you feel it's ready to be proposed use the Pull Request magic button of github

This way we can discuss the commits inside github code review tool and applying the patch once validated is a one click operation.

Thanks again, I'm going to take a look at #7 now.

/Paul

**Comment by JF9** [comment] 2011-04-15 15:58
I will try and make some time next week to provide this as a patch; I am a GitHub novice so I the learning curve will slow me down.
I noticed that start-domain exits with a non zero return and does not output to stderr but stdout, so I'll implement that as well.
Watch out.. I am running on glassfish 3.1

Again thanks.

**Comment by eskatos** [comment] 2011-04-15 16:24
You'll see, it's surprisingly easy once you know how to make a branch with git, github really ease the collaboration process.

Once you'll have done the pull request I'll test the code with glassfish v2.1 which is the other target before applying the patch.

Best regards

/Paul

**Comment by JF9** [comment] 2011-04-19 15:10
Okay I've completed this and committed my changes to my local repository, however when I use https://JF9@github.com/JF9/asadmin.git to push my changes to my fork, I get unauthorized. Should I be using the "Pull Request"  first?

**Comment by JF9** [comment] 2011-04-19 15:41
Sorry, user error with eclipse plugin. The changes have now been commited to my fork. What should I do next?

**Comment by eskatos** [comment] 2011-05-20 13:11
This one is now duplicate of the #9 PullRequest

**Closed as completed by eskatos** 2011-05-20 13:11 UTC
