### ISSUE TITLE
Glassfish v3 has deprecated asadmin syntax

### ISSUE THREAD

**Issue by emkayonline** [eskatos/asadmin#1] opened 2010-11-03 15:56 UTC
When using asadmin to deploy, etc with glassfish v3 a warning "deprecated syntax" is shown.
This is because the action command now comes after the generic parameters.  i have made the change in my fork and wondered if you would like to pull it into your main branch.
Change:
https://github.com/emkayonline/asadmin/commit/17c0eee64b31a19cf6998f5311d20741cd971480

**Comment by eskatos** [comment] 2010-11-03 18:42
Hello emkayonline,

Thanks for taking the time looking at the code.
BTW, this project support Glassfish V2 only right now.
Do your changes work with a V2 install ?

/Paul

**Comment by emkayonline** [comment] 2010-11-10 11:26
I've just tried it on glassfish 2.1.1 and sadly glassfish v2 doesn't like the command in the different order.  So I will keep my fork for glassfish 3.

**Comment by eskatos** [comment] 2010-11-10 13:14
Thanks for trying this. I do not have the need for Glassfish v3 support for now but it will raise sooner or later and this project will have to be refactored in order to support both v2 and v3.

As you are using it against a v3, I'm interested about reading about your findings if you come accross other incompatibilities.

**Comment by emkayonline** [comment] 2010-11-10 14:01
OK, np.  It is working well so far with the little change in command line argument order.  nice plugin by the way - clean and simple for glassfish users compared to cargo.

**Comment by eskatos** [comment] 2010-12-16 22:25
Duplicate of #2

**Closed as completed by eskatos** 2010-12-16 22:25 UTC
Labels: bug
