### ISSUE TITLE
Omitting certain parameters

### ISSUE THREAD

**Issue by nuukular** [eskatos/asadmin#17] opened 2012-06-15 14:04 UTC
Is there a way to NOT specify certain parameters? For instance I do not want to set the user and the passwordfile parameter, as I do not need them. 
If I do not set the user in the configuration section of the plug-in, it appears they are set to the default value.
If I specify the user as <user/> or <user></user> they still seem to be set to the default value.
How would I configure the plug-in to not provide certain parameters in the asadmin command line statement?

**Comment by eskatos** [comment] 2012-06-15 14:56
Credentials are mandatory only for certain asadmin commands, this project reflect this.
For example the PingConnectionPool command don't need credentials but the CreateConnectionPool one do.
Maybe some of the commands are marked as needing credentials whereas they don't.

What command where you trying to use?

**Comment by nuukular** [comment] 2012-06-15 15:00
Sorry for being not specific enough. I was referring to the deploy command, which in our case works without specifying the user and the password explicitly.

**Comment by eskatos** [comment] 2012-06-15 15:32
Did you change something in your glassfish setup so this command don't need credentials?

**Comment by nuukular** [comment] 2012-06-18 08:38
No, this actually is just a basic glassfish setup. I think this is the default. The admin console works without credentials out of the box as well. However, this is a minor issue. The asadmin works with the defaults you have set.

**Comment by eskatos** [comment] 2012-06-18 09:05
Are you sure you don't have any .asadmintruststore file at the default location?
If I remember correctly asadmin use this one as a default internally, the plugin doing the very same.

**Comment by nuukular** [comment] 2012-06-20 14:33
If there is any .asadmintruststore file, it must be part of the default glassfish installation. I actually never created one manually.

**Comment by eskatos** [comment] 2012-06-22 15:00
This file gets created when you login using the asadmin command line tool.

**Comment by eskatos** [comment] 2013-04-13 16:30
Not a bug.

**Closed as completed by eskatos** 2013-04-13 16:30 UTC
